package Files;

public class PayloadParctice {
	public static String postId() {
		String postIdPayload="[\r\n"
				+ "    {\r\n"
				+ "        \"postId\": 1,\r\n"
				+ "        \"id\": 1,\r\n"
				+ "        \"name\": \"id labore ex et quam laborum\",\r\n"
				+ "        \"email\": \"Eliseo@gardner.biz\",\r\n"
				+ "        \"body\": \"laudantium enim quasi est quidem magnam voluptate ipsam eos\\ntempora quo necessitatibus\\ndolor quam autem quasi\\nreiciendis et nam sapiente accusantium\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"postId\": 1,\r\n"
				+ "        \"id\": 2,\r\n"
				+ "        \"name\": \"quo vero reiciendis velit similique earum\",\r\n"
				+ "        \"email\": \"Jayne_Kuhic@sydney.com\",\r\n"
				+ "        \"body\": \"est natus enim nihil est dolore omnis voluptatem numquam\\net omnis occaecati quod ullam at\\nvoluptatem error expedita pariatur\\nnihil sint nostrum voluptatem reiciendis et\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"postId\": 1,\r\n"
				+ "        \"id\": 3,\r\n"
				+ "        \"name\": \"odio adipisci rerum aut animi\",\r\n"
				+ "        \"email\": \"Nikita@garfield.biz\",\r\n"
				+ "        \"body\": \"quia molestiae reprehenderit quasi aspernatur\\naut expedita occaecati aliquam eveniet laudantium\\nomnis quibusdam delectus saepe quia accusamus maiores nam est\\ncum et ducimus et vero voluptates excepturi deleniti ratione\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"postId\": 1,\r\n"
				+ "        \"id\": 4,\r\n"
				+ "        \"name\": \"alias odio sit\",\r\n"
				+ "        \"email\": \"Lew@alysha.tv\",\r\n"
				+ "        \"body\": \"non et atque\\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\\nquia voluptas consequuntur itaque dolor\\net qui rerum deleniti ut occaecati\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"postId\": 1,\r\n"
				+ "        \"id\": 5,\r\n"
				+ "        \"name\": \"vero eaque aliquid doloribus et culpa\",\r\n"
				+ "        \"email\": \"Hayden@althea.biz\",\r\n"
				+ "        \"body\": \"harum non quasi et ratione\\ntempore iure ex voluptates in ratione\\nharum architecto fugit inventore cupiditate\\nvoluptates magni quo et\"\r\n"
				+ "    }\r\n"
				+ "]";
		return postIdPayload ;
		
	}
	
	public static String comment() {
		String com="{\r\n"
		+ "    \"posts\": [\r\n"
		+ "        {\r\n"
		+ "            \"id\": 1,\r\n"
		+ "            \"title\": \"Post 1\"\r\n"
		+ "        },\r\n"
		+ "        {\r\n"
		+ "            \"id\": 2,\r\n"
		+ "            \"title\": \"Post 2\"\r\n"
		+ "        },\r\n"
		+ "        {\r\n"
		+ "            \"id\": 3,\r\n"
		+ "            \"title\": \"Post 3\"\r\n"
		+ "        }\r\n"
		+ "    ],\r\n"
		+ "    \"comments\": [\r\n"
		+ "        {\r\n"
		+ "            \"id\": 1,\r\n"
		+ "            \"body\": \"some comment\",\r\n"
		+ "            \"postId\": 1\r\n"
		+ "        },\r\n"
		+ "        {\r\n"
		+ "            \"id\": 2,\r\n"
		+ "            \"body\": \"some comment\",\r\n"
		+ "            \"postId\": 1\r\n"
		+ "        }\r\n"
		+ "    ],\r\n"
		+ "    \"profile\": {\r\n"
		+ "        \"name\": \"typicode\"\r\n"
		+ "    }\r\n"
		+ "}";
		return com;
		
	}
	
	public static String mina() {
		String name="[\r\n"
				+ "  {\r\n"
				+ "    \"name\" : \"Lindy\",\r\n"
				+ "    \"breed\" : \"Cymric\",\r\n"
				+ "    \"color\" : \"white\",\r\n"
				+ "    \"kittens\" : [\r\n"
				+ "      {\r\n"
				+ "        \"name\" : \"Percy\",\r\n"
				+ "        \"gender\" : \"m\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\" : \"Thea\",\r\n"
				+ "        \"gender\" : \"f\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\" : \"Annis\",\r\n"
				+ "        \"gender\" : \"f\"\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"name\" : \"Mina\",\r\n"
				+ "    \"breed\" : \"Aphrodite Giant\",\r\n"
				+ "    \"color\" : \"ginger\",\r\n"
				+ "    \"kittens\" : [\r\n"
				+ "      {\r\n"
				+ "        \"name\" : \"Doris\",\r\n"
				+ "        \"gender\" : \"f\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\" : \"Pickle\",\r\n"
				+ "        \"gender\" : \"f\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\" : \"Max\",\r\n"
				+ "        \"gender\" : \"m\"\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"name\" : \"Antonia\",\r\n"
				+ "    \"breed\" : \"Ocicat\",\r\n"
				+ "    \"color\" : \"leopard spotted\",\r\n"
				+ "    \"kittens\" : [\r\n"
				+ "      {\r\n"
				+ "        \"name\" : \"Bridget\",\r\n"
				+ "        \"gender\" : \"f\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\" : \"Randolph\",\r\n"
				+ "        \"gender\" : \"m\"\r\n"
				+ "      }\r\n"
				+ "    ]\r\n"
				+ "  }\r\n"
				+ "]";
		return name;
	}
	
	public static String webAutomation() {
		String courses="[\r\n"
				+ "  {\r\n"
				+ "    \"url\":\"rahulshettyacademy.com\",\r\n"
				+ "    \"services\":\"projectSupport\",\r\n"
				+ "	 \"expertise\":\"Automation\",\r\n"
				+ "	 \"courses\" :{\r\n"
				+ "\r\n"
				+ "\"WebAutomation\" :[\r\n"
				+ "  {\r\n"
				+ "\"courseTitle\":\"Selenium Webdriver java\",\r\n"
				+ "\"price\":\"50\"\r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"courseTitle\":\"Cypress\",\r\n"
				+ "\"price\":\"40\"\r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"courseTitle\":\"Protractor\",\r\n"
				+ "\"price\":\"40\"\r\n"
				+ "}\r\n"
				+ "],\r\n"
				+ "\r\n"
				+ "\"Api\" :[{\r\n"
				+ "\"courseTitle\":\"rest Assured Automation using java\",\r\n"
				+ "\"price\":\"50\"\r\n"
				+ "},\r\n"
				+ "{\r\n"
				+ "\"courseTitle\":\"Soup UI Webservises testing\",\r\n"
				+ "\"price\":\"40\"\r\n"
				+ "}\r\n"
				+ "],\r\n"
				+ "\r\n"
				+ "\"Mobile\" :[{\r\n"
				+ "\"courseTitle\":\"Appium Webservises testing\",\r\n"
				+ "\"price\":\"30\"\r\n"
				+ "}\r\n"
				+ "],\r\n"
				+ "\r\n"
				+ " \"instructor\":\"RahulShetty\", \r\n"
				+ "  \"linkedIn\" :\"https//www.linkedIn.com/in/rahul-shetty-trainer\"\r\n"
				+ "}}]";
		return courses;
	}
}
